Insert INTO CATEGORIES(NAME, CREATION_TIME_STAMP, UPDATE_TIME_STAMP)
VALUES ('shopping', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
Insert INTO CATEGORIES(NAME, CREATION_TIME_STAMP, UPDATE_TIME_STAMP)
VALUES ('leasing', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
Insert INTO CATEGORIES(NAME, CREATION_TIME_STAMP, UPDATE_TIME_STAMP)
VALUES ('bank loan', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());